remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Developer Experience
email: trucbinh@gmail.com
description: >-
  My Experience
twitter_username: trucbinh
github_username:  trucbinh
